[tools]
act = "latest"
actionlint = "latest"
ant = "latest"
"asdf:boris-ning-usds/asdf-azure-cli" = "latest"
"asdf:fartbagxp/asdf-trippy" = "latest"
"asdf:fartbagxp/asdf-oauth2c" = "latest"
"asdf:log2/asdf-step" = "latest"
awscli = "latest"
black = "latest"
"cargo:lstr" = "latest"
"cargo:rkik" = "latest"
"cargo:zizmor" = "latest"
cf = "latest"
cosign = "3.0.1"
deno = "latest"
dotnet = "latest"
flyctl = "latest"
gallery-dl = "latest"
github-cli = "latest"
"github:asciinema/asciinema" = "latest"
"github:clever/csvlint" = "latest"
"github:dolthub/dolt" = "latest"
"github:duckdb/duckdb" = "latest"
"github:google/yamlfmt" = "latest"
"github:kbknapp/cargo-outdated" = "latest"
"github:maxmind/mmdbinspect" = "latest"
"github:newren/git-filter-repo" = "latest"
"github:runpod/runpodctl" = "latest"
"github:seeyebe/gmap" = "latest"
"github:square/certigo" = "latest"
"github:trufflesecurity/trufflehog" = "latest"
"github:unfrl/dug" = "latest"
"github:versent/saml2aws" = "latest"
gitleaks = "latest"
go = "latest"
"go:github.com/boostsecurityio/poutine" = "latest"
"go:github.com/github/git-sizer" = "latest"
"go:github.com/htmlparser/htmlparser" = "latest"
"go:github.com/plutov/oq" = "latest"
"go:github.com/projectdiscovery/dnsx/cmd/dnsx" = "latest"
"go:github.com/projectdiscovery/httpx/cmd/httpx" = "latest"
"go:github.com/projectdiscovery/subfinder/v2/cmd/subfinder" = "latest"
"go:github.com/reteps/dockerfmt" = "latest"
"go:github.com/six-ddc/plow" = "latest"
"go:github.com/stacklok/frizbee" = "latest"
gradle = "8.9"
grype = "latest"
helm = "latest"
hugo = "latest"
java = "openjdk-21.0.2"
kind = "latest"
kubectl = "latest"
maven = "latest"
mdbook = "latest"
mitmproxy = "latest"
"npm:actions-up" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
node = "24"
oc = "latest"
packer = "latest"
pipx = "latest"
"pipx:asstosrt" = "latest"
"pipx:chardet" = "latest"
"pipx:checkov" = "latest"
"pipx:check-jsonschema" = "latest"
"pipx:copyparty" = "latest"
"pipx:datasette" = "latest"
"pipx:llm" = "latest"
"pipx:mkdocs" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pyasstosrt" = "latest"
"pipx:semgrep" = "latest"
"pipx:sslyze" = "latest"
"pipx:vastai" = "latest"
"pipx:zensical" = "latest"
pnpm = "latest"
poetry = "latest"
python = "3.13"
ripgrep = "latest"
ruby = "3.2.8"
ruff = "latest"
rust = "latest"
sbt = "1.10.7"
scala = "2.13.16"
shellcheck = "latest"
shfmt = "latest"
sqlite = "latest"
steampipe = "latest"
syft = "latest"
terraform = "latest"
terraformer = "latest"
trivy = "latest"
"ubi:praetorian-inc/noseyparker" = "latest"
uv = "latest"
websocat = "latest"
yarn = "latest"
yq = "latest"
yt-dlp = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "python"]
